### ISSUE TITLE
"Random" ProxyId runs into collisions on 'state' event emitters

### ISSUE THREAD

**Issue by cstim** [heisenware/vrpc#44]
**Describe the Bug**
If a client application uses VrpcRemote to register event listeners to remote objects and does so for a larger number of objects, the seemingly "random" `proxyId` (consisting of 2 bytes) is by far not random enough to prevent collisions. The erroneous behaviour is that event data is passed into the wrong callbacks.

In fact, in the Cybus project we easily run into the situation where so many proxy objects have been created that some of them use the same `proxyId`. When we then register for the `state` event of each of that object, we easily end up in a situation where the listener callback for one object's state erroneously receives the actual arguments intended for a different object's state. That means the vrpc callback mechanism for event notification is not reliable enough.

**Steps To Reproduce**

1. Create a large set of remote objects where each will emit a `state` event
2. Register the `state` event remotely using a VrpcRemote object: `proxy.on('state',(state) => console.log('got state')` but also keep track which object receives which state message (will require a slightly longer code example than this one-liner)
3. Once more than, say, 5000 objects have been created, and state listeners are registered, one can observe that the first listeners start to receive state notification that were not intended for them but instead for a different object.

**Expected Behavior**
The `on('eventName', ...)` registration should let the callback be triggered only on events by the intended remote object, not any others.

**Desktop (please complete the following information):**

- vrpc 2.3.2

**Additional context**
The problem is caused by the combination of the following factors:
- The `proxyId` is not very random because it consists only of 2 bytes https://github.com/heisenware/vrpc/blob/master/vrpc/VrpcRemote.js#L910
- The event subscription `id` adds the event name, but this can easily be constant (such as `'state'`) over many many objects https://github.com/heisenware/vrpc/blob/master/vrpc/VrpcRemote.js#L1056
- Upon storing the subscription, there is no initial check that the newly created proxyId and/or event id hasn't been used beforehand. https://github.com/heisenware/vrpc/blob/master/vrpc/VrpcRemote.js#L1057

We strongly suggest adding a collision check before using a newly generated `proxyId`, so that a newly created random identifier which is supposed to be locally unique should really be verified to be unique. Hence, in addition to `this._cachedSubscriptions`, there should probably be also something like a Set of `this._cachedProxyId` where each newly created proxyId should be marked as being used, until it is cleaned up again.

Note that simply creating longer proxyIds might make the problem smaller but will for sure not solve it completely. The only complete solution is to add a collision check in the creation of the `proxyId`.

**Comment by bheisen** [comment]
Yes, that's indeed a problem, thank you for reporting!

I will tackle the issue by prolonging the `proxyId` to 9 characters and base its generation on _nanoid_. With that we will have a collision probability of 1% after generating 19.008.000 ids. That should more then suffice for any "regular" application and solve your reported problem.

**Comment by cstim** [comment]
Thanks for picking this up quickly. However, I think you didn't touch the proxyId in VrpcRemote.js, https://github.com/heisenware/vrpc/blob/master/vrpc/VrpcRemote.js#L910  as IMHO the error in our system wasn't caused by a collision of the global IDs but rather the local IDs on the receiving end of a vrpc connection. 

If I understood our observed problem correctly, the local proxyId in our local VprcRemote object were generated often enough so that `this._cachedSubscriptions` in VrpcRemote ran into collisions, not the remote proxyId in VrpcAdapter or VrpcLocal. If  your quick calculation leads you to a statement of 1% probabilty of collision, I have to say, watch your step, because nobody will be satisfied if there is a 1% chance that your event listener receives an event it never subscribed to! This is unacceptable in a programming environment. Also, there's an obvious way how to avoid this in VrpcRemote.js line 910: Check for each generated local ProxyId that it's not in use. (Similar to database UUIDs which would first do a quick O(logN) search on whether a newly generated UUID is indeed unique. Not super-expensive but a much stronger assertion that the promised uniqueness is really valid.)

As for how many local proxy IDs in VrpcRemote might get generated: Let's assume a connectware service with 1000 resources. Let's assume it gets disabled/enabled every 6 minutes = 10 times per hour = 240 times per day, this makes already 240K IDs to be generated per day, and now we want to have this running for only 10 days without restarting = 2*10^6 IDs, and for sure we want to not have a 10% chance of collision but we want a 0% assertion that no event listener from `this._cachedSubscriptions` receives an event that was targeted to a different event listener instead.

**Comment by cstim** [comment]
So the actual solution was now implemented in commit  312b14712b797e34f76dee33d65e3f946ac3ede6 , thanks. Can you publish a version 2.5.2 so that this solution is available as published package? Thanks!
