### ISSUE TITLE
Fix crash on undefined oldInstances

### ISSUE THREAD

**Issue by cstim** [heisenware/vrpc#8]
In vrpc/VrpcRemote.js:169, if `oldInstances` is undefined (occurred here because of mqtt messages that came from a different client), the call `oldInstances.filter()`  will crash.

Please insert another guard in line 168, if `oldClassInfo.instances` is undefined but `oldClassInfo` was defined.

**Comment by bheisen** [comment]
Is fixed in current master and will appear in the next release.
